version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-builds:
    jobs:
      - run: yarn install
      - run: yarn ng build --prod
      - run: yarn ng test --single-run
jobs:
  build:
    docker: 
    - image: circleci/node:8-browsers



