version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker: 
      - image: circleci/node:15-browsers
    steps:

      - checkout
      - setup-remote-docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths: 
          - node_modules
          key:  v1-dependencies-{{ checksum "package.json" }}

      - run: yarn ng build --prod
      - run: yarn ng test --watch=false
      - run:
        command: |
          docker build -t vktest.azurecr.io/hello:1.0
        command: |
          docker login --usernane $DOCKER_USER --password $DOCKER_PASS vktest.azurecr.io
        command: |
          docker push vktest.azurecr.io/hello:1.0

