version: 2.1
orbs:
  node: circleci/node@15.3.0
workflows:
  node-tests:
    jobs:
     - node/test

  steps:
    -checkout

  -  run: yarn install

       
  -  run: yarn ng build --prod
  -  run: yarn ng test  --single-run

  

     
    