version: 2.1
orbs:
  node: circleci/node@15.3.0
workflows:
  node-tests:
    jobs:
     - node/test
    build:
      docker:
        - image: circleci/node:15-browsers
  steps:
    -checkout

  -  run: yarn install
  - save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum : "package.json" }}

       
  -  run: yarn ng build --prod
  -  run: yarn ng test  --single-run

  

     
    